//
// Created by Daniel on 22/03/2018.
//

#ifndef LCOMPILER_CONFIG_H
#define LCOMPILER_CONFIG_H

#define VAR_LEN_MAX 255
#define ARRAY_SIZE_MAX 4096
#define TAB_ASC2_SIZE 128
#define PROGRAM_LEN_MAX 8192
#define SYMBOL_TABLE_SIZE 40

#define LOWER_LIMIT_INTEGER -32768
#define UPPER_LIMIT_INTEGER 32767

#endif //LCOMPILER_CONFIG_H
