/* Exemplo de Programa na linguagem L */

int n;
char nome[50];
char flag;
final MAXITER = 10;

/* Programa Principal */

  flag <- 'A';
  flag <- 09Dh;

   if (n = 10) then
        writeln(n);
   else
        if( MAXITER ) then begin
            for n <- 0 to MAXITER step 1 do
                writeln(10);
            readln(id);
        end

   a[a] <- 1000;

   a[b[10/10]] <- d[(5*10)];

   for i <- 0DDh to (10*9) step 10 do begin
        readln(a);
   end

/* Programa Principal */

     write("Digite seu nome: ");
     readln(nome);

     for n <- 1 to MAXITER do begin
       if(1) then begin
            if(0) then ;
       end
       readln(id);
       writeln("Ola","hello",'c');
     end