/* Exemplo de Programa na linguagem L */

int n <- 9;
char nome[20];
int i,p <- 990;
int id <- -32768;
int a,b,d;
char flag <- 0FFh;
final MAXITER = 10;
final k = 'k';
final x = 0DDh;
int vet[4096];
int m[100], o[1];

/* Programa Principal */

  flag <- 'A';
  flag <- 09Dh;
  flag <- ' ';
  flag <- ' ';
  flag <- 'a';

   if (n = 10) then
        writeln(vet[1]);
   else
        if( MAXITER ) then begin
            for n <- 0 to MAXITER step 1 do
                writeln(10);
            readln(id);
        end

   if a = 1 or b = 10 then;
   if (k = 'c') or (x = 'd') then;
   if (k = 'c') or (b = 100) then;
   if (k = 0AAh) or (b = 100) and ( a = 1 ) then;
   if n > a then;
   if n < a then;
   if n >= a then;
   if n <= a then;
   if n <> a then;
   if not a then begin ; end

   a <- 20-10;
   a <- 20/10;
   a <- 20*10;
   a <- 20%10;

   a <- 1000;

   m[10] <- o[(5*10)];

   for i <- 10 to (10*9) step 10 do begin
        readln(a);
   end

/* Programa Principal */

     write("Digite seu nome: ");
     readln(nome);

     for n <- 1 to MAXITER do begin
       if(n < 10) then begin
            if(i <> p) then ;
       end

       writeln("Ola","hello",'c');
     end