/* Exemplo de Programa na linguagem L */

char array[10];
int a;
char c;
final MAX = 10;
int b[20];

/** Programa Principal **/

  for a <- 0 to MAX -1 do
      if( "Daniel" = "Daniel" ) then
            writeln(a, " true!");

   array <- "Daniel C.L";

   for a <- 0 to MAX -1 do
        write(array[a]);

  if( "Daniel" <> "daniel" ) then begin

  write("numero1: ");
  readln(b[0]);

  write("numero2: ");
  readln(b[1]);

  write("numero3: ");
  readln(b[2]);

  write(5);

  writeln(041h);

  write("Digite uma letra: ");
  readln(c);

  writeln("letra digitada: ", c);

  write("Digite um numero: ");
  readln(a);

  writeln("Num digitado - MAX: ", (a - MAX));
   writeln("Num digitado - b[0]: ", (a - b[1]));

  writeln('z');

  write("Digite seu nome: ");
  readln(array);

  writeln("Letra favorita: ", c);

  writeln(array," mito!");

  writeln(b[0],b[1],b[2]);

  writeln(array[0]);
  writeln(array[1]);
  writeln(array[2]);
  writeln(array[3]);
  writeln(array[4]);

  b[0] <- 192;
  b[1] <- 168;
  b[2] <- 0;
  b[3] <- 2;

  if( b[0] <> 192 ) then begin

  array <- "Rede A";
  writeln(array);
  writeln(b[0],".",b[1],".",b[2],".",b[3]);

  end

  c <- 'c';

  if( c <> 'd' ) then
     writeln("classe ", c);

end

if( "Daniel" <> "daniel" ) then
    writeln("T0");


if( "daniel" <> "Daniel"  ) then
    writeln("T1");

write("Digite seu nome: ");
readln(array);

if( "Daniel" <> array ) then
    writeln("T2");
